In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Web Scraping using BeautifulSoup

The objective of this project is to extract book information from a public website using BeautifulSoup and create a structured dataset for further analysis.

In [2]:
url = "https://books.toscrape.com/"

response = requests.get(url)

print(response.status_code)

200

In [9]:
soup = BeautifulSoup(response.text, "html.parser")

In [10]:
books = soup.find_all("article", class_="product_pod")

len(books)

20

In [11]:
book_data = []

In [12]:
for book in books:
    
    title = book.h3.a["title"]
    
    price = book.find("p", class_="price_color").text
    
    rating = book.find("p")["class"][1]
    
    availability = book.find("p", class_="instock availability").text.strip()
    
    book_data.append({
        "Title": title,
        "Price": price,
        "Rating": rating,
        "Availability": availability
    })

In [13]:
df = pd.DataFrame(book_data)

In [14]:
df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [15]:
df.to_csv("books.csv", index=False)

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         20 non-null     str
 1   Price         20 non-null     str
 2   Rating        20 non-null     str
 3   Availability  20 non-null     str
dtypes: str(4)
memory usage: 772.0 bytes

### Observation

- The dataset contains information about books scraped from the website.
- It includes four columns: Title, Price, Rating, and Availability.
- No missing values are present in the extracted data.

In [17]:
df.describe(include="all")

                       Title    Price Rating Availability
count                     20       20     20           20
unique                    20       20      5            1
top     A Light in the Attic  Â£51.77    One     In stock
freq                       1        1      6           20

### Observation

- The dataset contains categorical and text-based information.
- Book titles are unique, while ratings and availability contain repeated values.
- The summary provides an overview of the scraped dataset.

In [19]:
df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [20]:
df.tail()

,Title,Price,Rating,Availability
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,Three,In stock
16,Olio,Â£23.88,One,In stock
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,One,In stock
18,Libertarianism for Beginners,Â£51.33,Two,In stock
19,It's Only the Himalayas,Â£45.17,Two,In stock

### Observation

- The first and last records confirm that the data has been extracted correctly.
- Each row represents one book with its title, price, rating, and availability.

In [21]:
import os

print(os.path.exists("books.csv"))

True

# Data Story

This project demonstrates how web scraping can be used to collect structured data from a public website. Using BeautifulSoup, book information such as title, price, rating, and availability was extracted from the "Books to Scrape" website. The extracted data was organized into a Pandas DataFrame and exported as a CSV file. This custom dataset can be used for further data analysis, visualization, and machine learning applications.

# Key Insights

- Successfully scraped book information from a public website.
- Extracted four important attributes: Title, Price, Rating, and Availability.
- Created a structured dataset in CSV format.
- Demonstrated the use of requests, BeautifulSoup, and Pandas together.
- The generated dataset is ready for further analysis and visualization.

# Final Conclusion

- This project successfully implemented web scraping using Python and BeautifulSoup to collect book data from a public website.
- The extracted information was cleaned, organized, and saved into a CSV file, creating a reusable dataset for future analysis. 
- The project demonstrates fundamental web scraping techniques and the process of converting unstructured web data into structured data suitable for data analytics.